# -*- coding: utf-8 -*-
"""Tarea6ChristianBernal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLobIDQdYNzPiZccgqePugR8XDDVKFZG
"""

# Instalar pybind11 y cmake
!pip install pybind11
!apt-get install cmake

import pybind11
print(pybind11.get_cmake_dir())

# Crear el archivo nombre.cpp
code = """
#include <pybind11/pybind11.h>
#include <iostream>
#include <pybind11/stl.h> // Para la integraciÃ³n de STL

namespace py = pybind11;

std::string imprimir() {
    return "Hola, mi nombre es Christian";
}

PYBIND11_MODULE(nombre, m) {
    m.def("imprimir", &imprimir, "Función que imprime el nombre en pantalla");
}
"""

# Guardar el archivo nombre.cpp
with open("nombre.cpp", "w") as f:
    f.write(code)

# Crear el archivo CMakeLists.txt
cmake_code = """
cmake_minimum_required(VERSION 3.12)
project(nombre)

# Buscar donde esta instalado PyBind11
set(pybind11_DIR "/usr/local/lib/python3.10/dist-packages/pybind11/share/cmake/pybind11")
find_package(pybind11 REQUIRED)

# Agregar el modulo
add_library(nombre MODULE nombre.cpp)
set_target_properties(nombre PROPERTIES PREFIX "" SUFFIX ".so")

# Enlazar con PyBind11
target_link_libraries(nombre PRIVATE pybind11::module)
"""

# Guardar el archivo CMakeLists.txt
with open("CMakeLists.txt", "w") as f:
    f.write(cmake_code)

# Crear el directorio de compilación
!mkdir build

# Commented out IPython magic to ensure Python compatibility.
# %cd build

!cmake ..

!make

!ls

import sys
import os

# Añadir el directorio 'build' donde está el archivo .so
sys.path.append(os.path.abspath("/content/build"))

# Importar el módulo compilado
import nombre

nombre.imprimir()